### ISSUE TITLE
version is missing from previous step

### ISSUE THREAD

**Issue by jrobison-sb** [arbourd/concourse-slack-alert-resource#110]
I'm attempting to use this resource to send error notifications to slack whenever a pipeline fails, but doing so results in `version is missing from previous step`. Am I doing something wrong here?

My pipeline yaml:

```
---
resource_types:

- name: slack-notifier
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource
    tag: v0.16.2

resources:

# Other resources here...

- name: notify
  type: slack-notifier
  source:
    url: https://hooks.slack.com/services/... # devops_alerts


jobs:
- name: mfa-iam-report
  plan:
  - task: mfa-iam-report
    config:
      run: exit 1 # This job should fail so that the failure notification should go to slack

    on_failure:
      put: notify
      params:
        alert_type: failed

```

FWIW, this is my first usage of `arbourd/concourse-slack-alert-resource`, but not my first usage of a slack notification resource. Previously we used another community resource, but that resource is now unmaintained and so we are switching over to this resource. Previously, we had this other one which also used the `slack-notifier` name:

```
resource_types:

- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier
```

I suppose it's possible that there could be some leftover artifact from the old usage in Concourse's database or something, but I did also kill our Concourse server and let its ASG build a new server from scratch, so any cache of Docker images or something should now be gone.
