### ISSUE TITLE
Disabling at source is described in README but not present in latest image on dockerhub

### ISSUE THREAD

**Issue by jchesterpivotal** [arbourd/concourse-slack-alert-resource#35]
When I add the resource_type:

```yaml
- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource
```

Concourse will, by default, pull the image tagged as `latest`. In this case `latest` is synonymous with `v0.4.0`. That release was made on 5th July.

The README describes the ability to set `disable: true` on source, like so:

```yaml
- name: slack
  type: slack-alert
  source:
    url: ((slack-inbound-webhook))
    disable: true
```

But this feature was added in master on 10th July and is only present in the `master`-tagged image.

My suggestion is to cut a `v0.5.0` release, so that the README is in sync with behaviour.
