### ISSUE TITLE
No alert when job build errored

### ISSUE THREAD

**Issue by smoke** [arbourd/concourse-slack-alert-resource#41]
When the job `errored` (the orange color) there are no alerts to any channel.

I am wondering if I am using the `fixed` and `broke` alert types correctly as there is no example anywhere or am I missing something - may be using `ensure`?

I would appreciate some clarification if this is not a bug.

Here is my job definition:
```yaml
  - name: build-app-image
    serial: true
    on_success:
      aggregate:
        - put: team-alert
          params:
            alert_type: success
        - put: general-alert
          params:
            alert_type: fixed
    on_failure:
      aggregate:
        - put: team-alert
          params:
            alert_type: failed
        - put: general-alert
          params:
            alert_type: broke
    on_abort:
      put: team-alert
      params:
        alert_type: aborted

```
