### ISSUE TITLE
Way to notify specific people on slack

### ISSUE THREAD

**Issue by koustubhg** [arbourd/concourse-slack-alert-resource#43]
I want to notify certain users only based on the job name that failed. I tried using the message field like this
```
on_failure:
    put: notify
    params:
      alert_type: failed
      message: "Failed <@UDL2T4MRD>"
```
Although I can see I have been tagged, slack doesn't notify me ( I have notifications enabled when someone mentions my name.)

Is there a better way to do it?

**Comment by TamimiGitHub** [comment]
@koustubhg you will have to `<@userid|username>` to tag a user on slack from a slackbot

**Comment by arbourd** [comment]
@koustubhg I believe the lack of notifications is a limitation of the Slack incoming webhook. By design, it doesn't notify.

**Comment by southbanksoftwaredeveloper** [comment]
@arbourd 
I forked the repo to add the text field https://github.com/SouthbankSoftware/concourse-slack-alert-resource

e.g. you can tag by using slackid here
```
put: slack
          params:
            alert_type: failed
            text: "<@UDL2T4MRD>" #slack id
```
