### ISSUE TITLE
auto attach alerts all tasks

### ISSUE THREAD

**Issue by khabbabs** [arbourd/concourse-slack-alert-resource#48]
Is there anyway to add alerts to all the tasks in a pipeline?

**Comment by arbourd** [comment]
Not magically no. Because this is a resource, you still need to include it in your pipeline as a `put` task. The easiest way to normalize this is using yaml anchors:

```yaml
# anchor
slack-alert: &slack-alert
  on_success:
    put: alert
    params:
      alert_type: fixed
  on_failure:
    put: alert
    params:
      alert_type: broke

# pipeline

- name: example-job
  plan:
  - get: my-resource
    trigger: true
  - task: do-other-tasks-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Fake task"
    <<: *slack-alert
```
